steps:
  # Step 1: Install utilities (jq, zip) and find function directories
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y jq zip
        # Find all directories containing function.json
        FUNCTION_DIRS=$(find . -mindepth 1 -maxdepth 2 -type f -name "function.json" -exec dirname {} \;)
        echo "$FUNCTION_DIRS" > /workspace/function_dirs.txt

  # Step 2: For each directory found, process the function
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        while read dir; do
          echo "Processing function in $dir"
          # Parse JSON
          NAME=$(jq -r '.name' $dir/function.json)
          PROJECT_ID=$(jq -r '.project_id' $dir/function.json)
          REGION=$(jq -r '.region' $dir/function.json)
          RUNTIME=$(jq -r '.runtime' $dir/function.json)
          ENTRY_POINT=$(jq -r '.entry_point' $dir/function.json)
          SOURCE_DIR=$(jq -r '.source_directory' $dir/function.json)
          PUBLIC=$(jq -r '.public' $dir/function.json)
          ENV_VARS=$(jq -r '.env_vars | tojson' $dir/function.json)

          # Zip the source code
          cd $dir
          zip -r /workspace/${NAME}.zip $SOURCE_DIR
          cd /workspace

          # Upload to GCS bucket
          gsutil cp ${NAME}.zip gs://$_SOURCE_BUCKET/${NAME}.zip

          # Run Terraform
          # We'll run Terraform in the function directory
          cd $dir
          # init and apply
          docker run --rm -v $(pwd):/app -w /app \
            hashicorp/terraform:1.10.3 \
            sh -c "terraform init -upgrade && terraform apply -auto-approve \
              -var project_id=$_PROJECT_ID \
              -var name=$NAME \
              -var region=$REGION \
              -var runtime=$RUNTIME \
              -var entry_point=$ENTRY_POINT \
              -var source_archive_bucket=$_SOURCE_BUCKET \
              -var env_vars='$ENV_VARS' \
              -var public=$PUBLIC"
          cd /workspace
        done < /workspace/function_dirs.txt

substitutions:
  _PROJECT_ID: "saad-441415"
  _SOURCE_BUCKET: "cf-saad-441415"
