version: '3'
services:
  media-search-app-test:
    container_name: media-search-app-test
    build: .
    ports:
      - 8080:8080
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - NODE_ENV=development
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: always
    command: pnpm test:api

  elasticsearch:
    image: elasticsearch:8.16.1
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://elasticsearch:9200 >/dev/null || exit 1"
        ]
      interval: 10s
      timeout: 10s
      retries: 120
