version: '3'
services:
  media-search-app-dev:
    container_name: media-search-app-dev
    build: .
    ports:
      - 3000:8080
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - NODE_ENV=development
    depends_on:
      elasticsearch-dev:
        condition: service_healthy
    restart: always
    command: pnpm start

  elasticsearch-dev:
    image: elasticsearch:8.16.1
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-dev-data:/usr/share/elasticsearch/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://elasticsearch:9200 >/dev/null || exit 1"
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    
volumes:
  elasticsearch-dev-data:
    driver: local
    
